version: 0.2

phases:
  install:
    commands:
      - echo Started install phase...
      - apt-get update -y
  build:
    commands:
      - echo Started build phase...
      - npm install
      - npm install -g serverless
      - npm test -- --coverage
      - serverless -version
      - serverless deploy --verbose
  post_build:
    commands:
      - echo Build completed.