service: tic-tac-toe-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: us-west-2
  iamRoleStatements:
   - Effect: "Allow"
     Action: "s3:*"
     Resource: "arn:aws:s3:::${self:service}-${self:provider.stage}/*"
   - Effect: "Allow"
     Action: "sqs:createQueue"
     # allow the service to create queues with names like "tic-tac-toe-api-dev*"
     Resource: "arn:aws:sqs:*:*:${self:service}-${self:provider.stage}*"

functions:
  sample:
    handler: src/sample-function.handler
    events:
      - http: 'GET /sample'
    environment:
      BUCKET: ${self:service}-${self:provider.stage}
  sessions:
    handler: src/sessions.handler
    events:
      - http: 'POST /sessions'
    environment:
      BUCKET: ${self:service}-${self:provider.stage}
  commands:
    handler: src/commands.handler
    events:
      - http: 'POST /commands'

resources:
  Resources:
    AppBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName:
          Fn::Join:
            - ""
            - - ${self:service}
              - "-"
              - ${self:provider.stage}