service: tic-tac-toe-api

custom:
  resourcePrefix: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: us-west-2
  iamRoleStatements:
   - Effect: "Allow"
     Action: "s3:*"
     Resource: "arn:aws:s3:::${self:custom.resourcePrefix}/*"
   - Effect: "Allow"
     Action: "sqs:createQueue"
     # allow the service to create queues with names like "tic-tac-toe-api-dev*"
     Resource: "arn:aws:sqs:*:*:${self:custom.resourcePrefix}*"
   - Effect: "Allow"
     Action: "sns:Publish"
     Resource: "arn:aws:sns:*:*:*"

functions:
  sample:
    handler: src/sample-function.handler
    events:
      - http: 'GET /sample'
    environment:
      BUCKET: ${self:custom.resourcePrefix}
  sessions:
    handler: src/sessions.handler
    events:
      - http: 'POST /sessions'
    environment:
      BUCKET: ${self:custom.resourcePrefix}
  commands:
    handler: src/commands.handler
    events:
      - http: 'POST /commands'

resources:
  Resources:
    AppBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName: ${self:custom.resourcePrefix}
    IncomingCommandsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.resourcePrefix}-incoming-commands
    EventsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.resourcePrefix}-events
    CommandDispatchQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.resourcePrefix}-command-dispatch
        ReceiveMessageWaitTimeSeconds: 20