service: tic-tac-toe

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'