service: tic-tac-toe-api

custom:
  bucket: "tic-tac-toe-api-dev"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: us-west-2
  iamRoleStatements:
   - Effect: "Allow"
     Action: "s3:*"
     Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  sessions:
    handler: src/sessions.handler
    events:
      - http: 'POST /sessions'
    environment:
      BUCKET: ${self:custom.bucket}
  commands:
    handler: src/commands.handler
    events:
      - http: 'POST /commands'

resources:
  Resources:
    AppBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        BucketName:
          Fn::Join:
            - ""
            - - "tic-tac-toe-api-"
              - ${self:provider.stage}