service: tic-tac-toe

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-west-2

functions:
  sessions:
    handler: src/sessions.handler
    events:
      - http: 'POST /sessions'
  commands:
    handler: src/commands.handler
    events:
      - http: 'POST /commands'